[package]
name = "cardparse"
version = "0.1.0"
authors = ["aaron@bkrn.org"]
edition = "2018"

build = "build.rs"

[dependencies]
cardparse_derive = { path = "cardparse_derive" }

[build-dependencies]
skeptic = "0.13"

[dev-dependencies]
skeptic = "0.13"